### ISSUE TITLE
Port to Python

### ISSUE THREAD

**Issue by keithmcnulty** [keithmcnulty/onadata#5]
Seeking a volunteer to port this package to Python

**Comment by OlivierBinette** [comment]
Hi @keithmcnulty, I just messaged you about this on LinkedIn. I wrote Python packages and I currently do Python package development at my job. I'm also a proficient R programmer and published packages on CRAN, so I'd be able to help :)

**Comment by keithmcnulty** [comment]
Hi @OlivierBinette and thank you for offering your help.  In return I will be glad to add you to the list of acknowledged contributors in the introduction to the book.

`onadata` is purely a package of data sets, so I'm hoping it will be straightforward to port.  All the data sets for the `onadata` package can be found in CSV form at https://github.com/keithmcnulty/ona_book/tree/main/docs/data

A similar package for a previous book of mine is `peopleanalyticsdata`.  A port to Python for this was done and made available on PyPi and might be helpful reference for you.  The R package for `peopleanalyticsdata` is at https://github.com/keithmcnulty/peopleanalyticsdata, and the ported Python package is at https://github.com/akshayreddykotha/peopleanalyticsdata.

Please let me know if you need anything else to help you get started.

Many thanks again!

**Comment by OlivierBinette** [comment]
Hi @keithmcnulty, thanks for the information and references. I agree it's straightforward to port.

Could you email me at olivier.binette@duke.edu? We can talk about details of the contract. Note that I am a professional programmer (just getting started with consulting work), so I am looking for formal compensation. You can learn more about me here: https://olivierbinette.github.io/

**Comment by keithmcnulty** [comment]
Hi @OlivierBinette - the book is an open source community project.  It is free online, as are the packages supporting it. All income from print copies go to good causes, so this is not paid work.  Understand if that is not of interest to you.  Many thanks!

**Comment by OlivierBinette** [comment]
@keithmcnulty I understand, I also have my own open source projects :) Best of luck!
